c1

diff --git a/.github/workflows/ci-direct-docker.yml b/.github/workflows/ci-direct-docker.yml
--- a/.github/workflows/ci-direct-docker.yml
+++ b/.github/workflows/ci-direct-docker.yml
@@ -156,8 +156,15 @@ jobs:
             -e SPRING_DATASOURCE_URL=jdbc:mysql://myproject-mysql:3306/myprojectdb \
             -e SPRING_DATASOURCE_USERNAME=root \
             -e SPRING_DATASOURCE_PASSWORD=2702 \
-            -v /tmp/shared_data:/app/shared_data myproject1-app:latest
+            #-v /tmp/shared_data:/app/shared_data \
+            myproject1-app:latest
           echo "Spring Boot application is running."
+
+      # Thêm step kiểm tra log chi tiết của MySQL
+      - name: Check MySQL Logs
+        run: |
+          echo "Checking MySQL container logs..."
+          docker logs myproject-mysql || echo "Failed to retrieve MySQL logs"
 
       # 11. Kiểm tra trạng thái container
       # Liệt kê tất cả các container để kiểm tra trạng thái, xem container nào đang chạy hoặc đã dừng.
